cloud:
  aws:
    region:
      static: eu-west-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: xxxxx
      secret-key: xxxxx
    end-point:
      uri: https://sqs.eu-west-1.amazonaws.com/xxxxx/MyQueue
